title: SANDYPLAY
description: A description of your site goes here

# This is the most important part for your specific site!
url: "https://sandytalks.github.io"
baseurl: "/SANDYPLAY"

# Choose your theme here
theme: jekyll-theme-cayman
